version: '3.8'

services:
  frontend:
    build:
      context: .
    container_name: refine_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - laravel


networks:
  laravel:
    external: true